In [10]:
import numpy as np;
list = [2,4,6,8];
numpy_array = np.array(list);
numpy_multi_dimension = np.array([[1,2,3],[4,5,6],[7,8,9]]);
print(list);
print(numpy_array);
print(numpy_multi_dimension);
print("type of list", type(list));
print("type of matrix",type(numpy_multi_dimension));



[2, 4, 6, 8]
[2 4 6 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type of list <class 'list'>
type of matrix <class 'numpy.ndarray'>


#Numpy Functions Part1


In [23]:
import numpy as np
arr = np.arange(5,20,5)
arr

array([ 5, 10, 15])

In [21]:
lspace = np.linspace(1,10,10);
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
zeros = np.zeros([4,5]);
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
ones = np.ones([4,5]);
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
eyes = np.eye(5);
eyes

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
narr = np.arange(0,10)
nlist = np.array([[1,2,3,4],[5,6,7,8]])
reshape = narr.reshape(5,2);
reshape

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
np.sin(4)
np.sin(nlist)
np.tan(4)

1.1578212823495775

In [45]:
np.exp(2)
np.log(2)
np.log10(2)

0.3010299956639812

In [8]:
import pandas as pd;
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5